dist:
  name: otelcol-orb
  description: OpenTelemetry Collector for Orb
  version: 0.0.1-maestro
  output_path: ./dist
  otelcol_version: 0.93.0

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.91.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.87.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.91.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.87.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.87.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/zpagesextension v0.91.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.91.0

